name: flipbook
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
#  sdk: ">=3.4.3 <4.0.0"
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  path:
  document_scanner_flutter:
    git:
      url: https://github.com/sanjeevinnobit/document_scanner_flutter.git
      ref: master

  ffmpeg_kit_flutter_full_gpl:
  shared_preferences: ^2.2.3
  app_tracking_transparency: ^2.0.5
  flutter_document_scanner: ^1.1.2
  tapioca: ^1.0.6+1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  jiffy: ^6.2.1
  carousel_slider: ^4.2.1
  image_picker: ^1.1.2
#  images_picker: ^1.2.11
  path_provider: ^2.1.3
#  document_scanner_flutter: ^0.2.7
  permission_handler: ^11.3.1
  image_gallery_saver: ^2.0.3
#  ffmpeg_kit_flutter: ^5.1.0
  fluttertoast: ^8.2.6
  provider: ^6.1.2
  media_scanner: ^2.1.0
  share_plus: ^9.0.0
  sqflite: ^2.3.3+1
  google_mobile_ads: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^8.0.0
dependency_overrides:
  photo_view: ^0.15.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"
